import os
import time
import base64
from typing import Any, Dict
from openai import OpenAI
from src.harness.node.base import BaseNode
from src.harness.enums import LogType
from src.utils.config import AGENT_VM_DIR


class Node(BaseNode):
    """大模型图片生成器：支持文生图、图生图编辑、透明背景，并通过 ARTIFACT 投递给前端看板"""

    async def execute(self, inputs: Dict[str, Any], context: Any) -> Dict[str, Any]:
        self.log(context, "SYSTEM", "🎨 [图片生成] 节点启动")

        prompt = inputs.get("prompt")
        if not prompt:
            raise ValueError("必须提供 prompt (画面描述提示词)")

        api_key = inputs.get("api_key")
        base_url = "https://api.openai.com/v1"

        if not api_key:
            graph_name = getattr(context, "graph_name", "default")
            env_cache = getattr(context, "_global_env_cache", {}).get(graph_name, {})
            api_key = env_cache.get("OPENAI_API_KEY")
            base_url = env_cache.get("API_BASE_URL", base_url)

        if not api_key:
            raise ValueError("缺失 OpenAI API Key，请通过连线或 Env Loader 配置")

        client = OpenAI(api_key=api_key, base_url=base_url)

        size = self.config.get("size", "1024x1024")
        quality = self.config.get("quality", "high")
        output_format = self.config.get("output_format", "png")
        background = self.config.get("background", "auto")
        n_count = int(self.config.get("n", "1"))

        kwargs = {
            "model": "gpt-image-1",
            "prompt": prompt,
            "size": size,
            "quality": quality,
            "output_format": output_format,
            "n": n_count,
        }

        if background == "transparent" and output_format == "png":
            kwargs["background"] = "transparent"

        source_image_path = inputs.get("source_image")

        saved_paths = []
        html_img_tags = []

        try:
            if source_image_path and os.path.exists(source_image_path):
                self.log(
                    context,
                    "SYSTEM",
                    f"🖌️ [图片生成] 检测到原图，切换为图片编辑模式: {source_image_path}",
                )
                with open(source_image_path, "rb") as f:
                    source_b64 = base64.standard_b64encode(f.read()).decode("utf-8")

                kwargs["image"] = [
                    {
                        "type": "input_image",
                        "image_url": f"data:image/png;base64,{source_b64}",
                    }
                ]
                result = client.images.edit(**kwargs)
            else:
                self.log(
                    context,
                    "SYSTEM",
                    f"✨ [图片生成] 开始文生图 (Size: {size}, Quality: {quality})...",
                )
                result = client.images.generate(**kwargs)

            os.makedirs(AGENT_VM_DIR, exist_ok=True)
            timestamp = int(time.time())

            for idx, img_data in enumerate(result.data):
                b64_str = img_data.b64_json
                if not b64_str:
                    continue

                image_bytes = base64.b64decode(b64_str)
                filename = f"gen_img_{timestamp}_{idx}.{output_format}"
                file_path = os.path.join(AGENT_VM_DIR, filename)

                with open(file_path, "wb") as f:
                    f.write(image_bytes)
                saved_paths.append(file_path)
                self.log(
                    context, "SYSTEM", f"💾 [图片生成] 图片已存入沙盒: {file_path}"
                )

                html_img_tags.append(
                    f'<img src="data:image/{output_format};base64,{b64_str}" '
                    f'style="max-width:100%; border-radius: 12px; border: 4px solid #1a1a1a; box-shadow: 6px 6px 0px #1a1a1a;" />'
                )

            if html_img_tags:
                gallery_html = f"""
                <!DOCTYPE html>
                <html>
                <body style="margin:0; padding:20px; background:#fdfaf5; display:flex; flex-direction:column; gap:20px; align-items:center;">
                    <div style="font-family: sans-serif; font-weight: bold; color: #1a1a1a; margin-bottom: 10px;">
                        🎨 Generated by GPT-Image-1
                    </div>
                    {"".join(html_img_tags)}
                </body>
                </html>
                """
                self.log(context, LogType.ARTIFACT, gallery_html)
                self.log(
                    context, "SYSTEM", "✅ [图片生成] 已成功向前端推送可视化视图！"
                )

        except Exception as e:
            self.log(context, "ERROR", f"❌ [图片生成] API 调用或处理失败: {e}")
            raise RuntimeError(f"图片生成失败: {e}")

        return {"image_paths": saved_paths}
